### ISSUE TITLE
Do not swallow body on InvalidStatusCode

### ISSUE THREAD

**Issue by Palmik** [jpopesculian/reqwest-eventsource#11]
It would be great to not swallow the response body in case of an `InvalidStatusCode`, in order to be able to propagate better error messages upstream:

https://github.com/jpopesculian/reqwest-eventsource/blob/181e41ee35fdc6c5ff1bc3b8dfc14d1f964898f1/src/event_source.rs#L106

**Comment by jpopesculian** [comment]
hi @Palmik! I can do that! I'll need to make a new major release though, as this would be a breaking change to the API. I'll probably bundle it up with a wasm support update

**Comment by Palmik** [comment]
Thank you!

**Comment by Palmik** [comment]
Here's my temporary solution in the meantime, feel free to use: https://github.com/Palmik/reqwest-eventsource/commit/5aa7b417b5dca4624a304cb441ac5fe1e363f965

**Comment by phayes** [comment]
I was JUST about to open this ticket. I'm getting an error from a server with an error and I have NO idea what it says!  Glad to see it's already being worked on.
