### ISSUE TITLE
Upgrade reqwest 0.12

### ISSUE THREAD

**Issue by sigoden** [jpopesculian/reqwest-eventsource#19]
https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0

**Comment by sigoden** [comment]
[Reqwest v0.12](https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0) upgrades hyper, http and http-body to v1. It seems like a minor version update, but its impact is huge.

[Reqwest v0.11](https://github.com/seanmonstar/reqwest/releases/tag/v0.11.0) released on January 6, 2021. It's been a long time since reqwest v0.11 to v0.12.

Can you release a new version soon? @jpopesculian

**Comment by jpopesculian** [comment]
oh sorry! just saw this! yup i'll take a look and release this tomorrow (:

**Comment by jpopesculian** [comment]
Closed with #20 (: thanks
