### ISSUE TITLE
eventsource_stream 404

### ISSUE THREAD

**Issue by RustPanda** [jpopesculian/reqwest-eventsource#3]
Hello. You removed the crate eventsource_stream from GitHub, won't you stick with it anymore?

**Comment by jpopesculian** [comment]
hey @RustPanda I have no idea, how that repo turned private. I made it public and am investigating now. Thanks for making me aware

**Comment by jpopesculian** [comment]
I don't know if github offers a timeline for repo's but it seems to me that the repo was probably always private by mistake. Again thanks for pointing this out
