### ISSUE TITLE
New message ready callback

### ISSUE THREAD

**Issue by nab-os** [jpopesculian/reqwest-eventsource#4]
It would be nice to have a way to use callbacks instead of using `.await`.
Something like this:
```
stream.on_message_ready(|event| {
    //called each time a new Poll<...> is ready
    [...]
});
```
It would not block the thread.
I did not find how to do it the way it currently is.

**Comment by jpopesculian** [comment]
Hi @nab-os! The `eventsource` method returns a `Stream` object. Check out the extensions for the [`futures` crate](https://docs.rs/futures/0.3.21/futures/stream/index.html) for easy ways to handle the events in a more functional style
