### ISSUE TITLE
Non-200 responses should throw errors

### ISSUE THREAD

**Issue by dunglas** [jpopesculian/reqwest-eventsource#7]
According to the spec, the event stream should be parsed only if the status code of the response is 200. That's currently not implemented.

Regarding other codes, 301 and 307 redirections must be followed (already handled properly). 204 is a hint telling the client to not reconnect (not handled). Any other status code must throw an error.

I fear that a new API is required to handle this properly (#6 could probably be fixed by this redesign too). If you want @jpopesculian, I can try to work on a patch.

**Comment by jpopesculian** [comment]
Hello again @dunglas! Yeah I think you're totally right, that I also want to bring this closer to spec and how the browser would handle these things. I'm going to read over the spec and do a better redesign of the `EventsourceRequestBuilder` object

**Comment by dunglas** [comment]
@jpopesculian I have a tiny patch almost ready. I'll open a PR in a few minutes.

**Comment by dunglas** [comment]
@jpopesculian see https://github.com/jpopesculian/reqwest-eventsource/pull/8/files
